{
 "title": "Tempo - Benchmarking",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(reth_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transactions per Block",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(avg(reth_tempo_payload_builder_total_transactions_last{namespace=\"$namespace\"}) by (job), \"job\", \"$1\", \"job\", \"^$namespace/(.*)\")",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(reth_tempo_payload_builder_block_time_millis{namespace=\"$namespace\", quantile=~\"0.5|0.9|0.95|0.99\"}) by (quantile) < 5000",
     "legendFormat": "{{job}} p{{quantile}}"
    }
   ]
  },
  { "title": "Transaction Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Non-AA Transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(avg(reth_transaction_pool_total_transactions{namespace=\"$namespace\"}) by (job), \"job\", \"$1\", \"job\", \"^$namespace/(.*)\")",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "AA Transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(avg(reth_transaction_pool_aa_2d_total_transactions{namespace=\"$namespace\"}) by (job), \"job\", \"$1\", \"job\", \"^$namespace/(.*)\")",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Building", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(avg(reth_tempo_payload_builder_total_transaction_execution_duration_seconds{namespace=\"$namespace\", quantile=~\"0.5|0.9|0.95|0.99\"}) by (job, quantile), \"job\", \"$1\", \"job\", \"^$namespace/(.*)\")",
     "legendFormat": "{{job}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Finalization (state root) Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(avg(reth_tempo_payload_builder_payload_finalization_duration_seconds{namespace=\"$namespace\", quantile=~\"0.5|0.9|0.95|0.99\"}) by (job, quantile), \"job\", \"$1\", \"job\", \"^$namespace/(.*)\")",
     "legendFormat": "{{job}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Total Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(avg(reth_tempo_payload_builder_payload_build_duration_seconds{namespace=\"$namespace\", quantile=~\"0.5|0.9|0.95|0.99\"}) by (job, quantile), \"job\", \"$1\", \"job\", \"^$namespace/(.*)\")",
     "legendFormat": "{{job}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Gas Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "si: gas/s" } },
   "targets": [
    {
     "expr": "label_replace(avg(reth_tempo_payload_builder_gas_per_second_last{namespace=\"$namespace\"}) by (job), \"job\", \"$1\", \"job\", \"^$namespace/(.*)\")",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(avg(reth_sync_execution_execution_histogram{namespace=\"$namespace\", quantile=~\"0.5|0.9|0.95|0.99\"}) by (job, quantile), \"job\", \"$1\", \"job\", \"^$namespace/(.*)\")",
     "legendFormat": "{{job}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "State Root Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(avg(reth_sync_block_validation_state_root_histogram{namespace=\"$namespace\", quantile=~\"0.5|0.9|0.95|0.99\"}) by (job, quantile), \"job\", \"$1\", \"job\", \"^$namespace/(.*)\")",
     "legendFormat": "{{job}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Total Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(avg(reth_consensus_engine_beacon_new_payload_latency{namespace=\"$namespace\", quantile=~\"0.5|0.9|0.95|0.99\"}) by (job, quantile), \"job\", \"$1\", \"job\", \"^$namespace/(.*)\")",
     "legendFormat": "{{job}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Gas Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "si: gas/s" } },
   "targets": [
    {
     "expr": "label_replace(avg(reth_consensus_engine_beacon_new_payload_gas_per_second_last{namespace=\"$namespace\"}) by (job), \"job\", \"$1\", \"job\", \"^$namespace/(.*)\")",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "CPU usage/limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"tempo-node\"}[5m])) by (pod)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", container=\"tempo-node\"}) by (pod)",
     "legendFormat": "{{pod}} - limit"
    }
   ]
  },
  {
   "title": "Memory usage/limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"tempo-node\"}) by (pod)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", container=\"tempo-node\"}) by (pod)",
     "legendFormat": "{{pod}} - limit"
    }
   ]
  },
  { "title": "State Provider Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Account Fetch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(reth_sync_state_provider_account_fetch_latency{namespace=\"$namespace\", quantile=\"0.5\"} < 0.0001) by (source)",
     "legendFormat": "{{source}} p50"
    }
   ]
  },
  {
   "title": "Storage Fetch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(reth_sync_state_provider_storage_fetch_latency{namespace=\"$namespace\", quantile=\"0.5\"} < 0.001) by (source)",
     "legendFormat": "{{source}} p50"
    }
   ]
  },
  {
   "title": "Code Fetch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(reth_sync_state_provider_code_fetch_latency{namespace=\"$namespace\", quantile=\"0.5\"} < 0.00001) by (source)",
     "legendFormat": "{{source}} p50"
    }
   ]
  },
  {
   "title": "Disk Read latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total[1m])/clamp_min(irate(node_disk_reads_completed_total[1m]), 1)",
     "legendFormat": "{{instance}} ({{device}})"
    }
   ]
  }
 ]
}