name: Release PR

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  alloy:
    name: Alloy Release PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.TEMPO_GITHUB_PAT }}
          persist-credentials: true

      - name: Keep only alloy changelog entries
        run: python3 scripts/publish/utils.py filter_changelogs alloy

      - uses: tempoxyz/changelogs@master
        with:
          branch: changelog-release/alloy
          conventional-commit: true
          post-version-command: cargo update -w
          github-token: ${{ secrets.TEMPO_GITHUB_PAT }}

  revm:
    name: Revm Release PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.TEMPO_GITHUB_PAT }}
          persist-credentials: true

      - name: Keep only revm changelog entries
        run: python3 scripts/publish/utils.py filter_changelogs revm

      - uses: tempoxyz/changelogs@master
        with:
          branch: changelog-release/revm
          conventional-commit: true
          post-version-command: cargo update -w
          github-token: ${{ secrets.TEMPO_GITHUB_PAT }}
